### PR TITLE
Port of node-boyd to node.js v0.12

### PR DESCRIPTION
**Pull request by christoph-heiss**
This pull request contains a small cleanup and a port to node.js v0.12.

I tested harrogate under node.js v0.12 and it seems to run fine, I did not experience any differences between v0.10 and v0.12.

### CODE REVIEW

**Comment by PhilipTrauner** [comment]
Has this been forgotten or is there a reason this doesn't get merged?

**Comment by zeltner** [comment]
Thanks for your reminder. I was busy when I saw your request and then I
simply forgot it. I'll have a look and merge it today afternoon. Btw.,
great job, node-boyd was the only reason why we had to stick to node.js
v0.10

**Comment by christoph-heiss** [comment]
Sorry to bring this PR up again, but what about the npm-package?
It should be updated as well.

**Comment by zeltner** [comment]
We are currently in the process of removing node-boyd as a harrogate dependency and replacing it with [boyd](https://github.com/kipr/boyd) + [daylite](https://github.com/kipr/daylite) (probably it will happen this weekend). This means node-boyd is no longer under active development and a new npm-package release is not planned.
Sorry because of the frequent and drastic design changes but we are still in an very early development phase. Nevertheless, thank you for contributing and I hope that you will continue to do so.

**Pull request merged**
